apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    run: server
spec:
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    run: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
        - name: server
          image: simformniki/server-docker:2
          ports:
            - containerPort: 8080
